### ISSUE TITLE
NPM dependencies error

### ISSUE THREAD

**Issue by kowyo** [BasedHardware/OpenGlass#31]
Hi, I am using nvm with node.js 20.14.0(LTS)

I installed the dependencies by using the commands in README:

```bash
npm install
```
There were lots of deprecated waring btw.

but when I ran `npm start`, it gave errors like this:

```
Logs for your project will appear below. Press Ctrl+C to exit.
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:207:21)
Emitted 'error' event on NodeWatcher instance at:
    at FSWatcher._checkedEmitError (/Users/kowyo/Documents/OpenGlass/node_modules/metro-file-map/src/watchers/NodeWatcher.js:82:12)
    at FSWatcher.emit (node:events:519:28)
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:213:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}

Node.js v20.14.0
```

Would appreciate it if anyone knows how to fix this.

**Comment by GALA009** [comment]
执行 npm start 之后，你是不是选择运行在web端？

**Comment by kowyo** [comment]
Yes

**Comment by GALA009** [comment]
看报错应该是使用了 fs 方法报错，你在 `package.json` 文件中，新增 `
browser: {
    fs: false
}
`

**Comment by kowyo** [comment]
@GALA009 感谢回复，我收到了邮件，这里看不到了，但感觉你分析的很有道理，谢谢（GitHub 一般我不怎么用中文回复，见谅）

**Comment by kowyo** [comment]
Thank you @GALA009 , I solved it by adding

```json
"browser": {
    "fs": false
  }
```

to the end of package.json.

**Comment by MazokuXMakorov** [comment]
I am getting this error: **bash: npm: command not found**
when I try to use the command: **npm install**
can someone pls help?

**Comment by kowyo** [comment]
> I am getting this error: **bash: npm: command not found** when I try to use the command: **npm install** can someone pls help?

It’s a very basic error, I suggest you google it directly.
