### ISSUE TITLE
why my QR code looks ugly

### ISSUE THREAD

**Issue by F4irytale** [BasedHardware/OpenGlass#45]
![QQ截图20240709190532](https://github.com/BasedHardware/OpenGlass/assets/41540902/1908f023-ba44-4264-af5e-a4780a33274c)

**Comment by HaoHoo** [comment]
maybe you just need to change terminal fonts.

**Comment by F4irytale** [comment]
> maybe you just need to change terminal fonts.

thanks ，not support GBK
